/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/head/avatar.vue')['default']
    ComfortCenter: typeof import('./src/components/meunContent/ComfortCenter.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommonSense: typeof import('./src/components/meunContent/CommonSense.vue')['default']
    DiagnosticTests: typeof import('./src/components/meunContent/DiagnosticTests.vue')['default']
    Editor: typeof import('./src/components/forum/editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSpinner: typeof import('element-plus/es')['ElSpinner']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FunClass: typeof import('./src/components/aside/FunClass.vue')['default']
    Judgment: typeof import('./src/components/quiz/Judgment.vue')['default']
    MultiChoice: typeof import('./src/components/quiz/MultiChoice.vue')['default']
    PostCard: typeof import('./src/components/forum/PostCard.vue')['default']
    QuizResult: typeof import('./src/components/quiz/QuizResult.vue')['default']
    Quote: typeof import('./src/components/aside/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortAnswer: typeof import('./src/components/quiz/ShortAnswer.vue')['default']
    SingleChoice: typeof import('./src/components/quiz/SingleChoice.vue')['default']
    TeensPsy: typeof import('./src/components/meunContent/TeensPsy.vue')['default']
    Text: typeof import('./src/components/other/text.vue')['default']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
    UDivider: typeof import('undraw-ui')['UDivider']
    UFold: typeof import('undraw-ui')['UFold']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
